Metrics/BlockLength:
  # Exclude:
  #  - 'path/to/excluded/file.rb'
  Max: 30

Metrics/MethodLength:
  Max: 20
  
Metrics/AbcSize:
  Max: 15
 # Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10
